name: E2E Detox Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Build iOS app
      run: yarn build:ios

    - name: Run Detox tests
      run: yarn detox test --configuration ios.sim